version: '0.1.{build}' 
configuration:
- Debug 
platform: Any CPU 
image: Visual Studio 2017

environment: 
 DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0") 

build_script:
- build

test_script:
- build-test
- run.cmd "src\CoreCover.Tests\bin\Any CPU\Debug\netcoreapp1.0"

after_test:
- '%USERPROFILE%\.nuget\packages\coveralls.io\1.3.4\tools\coveralls.net.exe --opencover coverage.xml --r %COVERALLS_TOKEN% -f'
- pack-all

artifacts:
- path: '**\*.nupkg'

deploy:
  - provider: NuGet
    server: 
    api_key:
      secure: Hh52nD8i4YR/X5yRRaqWNchtVaH3/IvAzl9XcGPsrfQI0DnvJB9Odeju0e5yIG4D
    artifact: /.*\.nupkg/
