version: '0.1.{build}' 
configuration:
- Debug 
#- Release
platform: Any CPU 
image: Visual Studio 2017

environment: 
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COVERALLS_TOKEN:
    secure: W6ZK9C66pG2Ihkikl3Kybq/FGBKLKUzJnQjv8PS8m2SvEicfA6N5t1J0nLb/oyT5

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- nuget setapikey %myget_secure_key% -source https://www.myget.org/F/pjbgf/api/v3/index.json -Verbosity quiet
- nuget sources add -Name MyGet -Source https://www.myget.org/F/pjbgf/api/v3/index.json

build_script:
- build

#after_build:
#- dotnet pack src\CoreCover\CoreCover.csproj

test_script:
- build-test
- dotnet %USERPROFILE%\.nuget\packages\CoreCover\0.1.0-prerelease003\tools\netcoreapp1.1\CoreCover.dll src\CoreCover.Sample.Tests\bin\Debug\netcoreapp1.1\

after_test:
- '%USERPROFILE%\.nuget\packages\coveralls.net\0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml --repoToken %COVERALLS_TOKEN% --commitId %APPVEYOR_REPO_COMMIT% --commitBranch %APPVEYOR_REPO_BRANCH% --commitAuthor "%APPVEYOR_REPO_COMMIT_AUTHOR%" --commitEmail "%APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%" --commitMessage "%APPVEYOR_REPO_COMMIT_MESSAGE%" --jobId %APPVEYOR_BUILD_ID% --useRelativePath'

#artifacts:
#  - path: '**\*.nupkg'

#deploy:
#  - provider: NuGet
#    server: https://ci.appveyor.com/nuget/pjbgf/api/v2/package
#    api_key:
#      secure: kBraVpfC1aObEmg12ev0RD1x4UkYr7ajTE3ZKgtm+h4=
#    artifact: /.*\.nupkg/
    
# cache:
# - '%USERPROFILE%\.nuget\packages'
