version: '1.0.{build}' 
configuration: Debug 
platform: Any CPU 
image: Visual Studio 2017

environment: 
 DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0") 

build_script:
- build

test:
- build-test

cache:
- '%USERPROFILE%\.nuget\packages'
